### ISSUE TITLE
Github Pages Error..

### ISSUE THREAD

**Issue by hi-jin** [hi-jin/blog#1]
Your site is having problems building: Unable to build page. Please try again later.
해결법 아시는 분 ㅠㅠ

지금 레포 너무 많이 리셋해서 잠깐 오류난 거라고 생각하고, 일단 내일 시도는 하려는데,,

**Comment by stevehan00** [comment]
Repo이름을 github id로 해야하지 않나요

**Comment by hi-jin** [comment]
dd 했는데 오류나서 지금 바꿔놨음요
